name: CI

on:
  pull_request:
    branches: [master]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
          - macos-latest
        python:
          - 3.8
          - 3.9
          - "3.10"
          - "3.11"

    steps:
      - uses: actions/checkout@v4.1.1
        with:  # no need for the history
          fetch-depth: 1
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v5.0.0
        with:
          python-version: ${{ matrix.python }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          pip install --upgrade --force-reinstall --no-cache-dir --editable=".[test]"
      - name: Test with pytest
        run: |
          pytest -sv pydra_ml/tests/test_classifier.py
